spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 12345






mybatis:
  mapper-locations: classpath*:**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: DEBUG
